### ISSUE TITLE
Add ARM architeture to README

### ISSUE THREAD

**Issue by hearnsj** [JuliaMath/BFloat16s.jl#10]
ARM have announced BFloat16 support for the ARM-8 architecture.
Suggest change README.md to read:

This package defines the BFloat16 data type. Google's Cloud TPUs implement this data type.
ARM have announced that the next ARMv8-A architecure will support BFLoat16 instructions.

**Comment by Keno** [comment]
Intel also. I'd take a PR to expand the readme with links to relevant documentation for upcoming architectures.
