### ISSUE TITLE
Potential eps Function

### ISSUE THREAD

**Issue by jprhyne** [JuliaMath/BFloat16s.jl#24]
Hello, I've been working with unit roundoff and we recently expanded our considerations to testing with BFloat16. I wrote a little function at the bottom that returned 2^(-7) when one types 
`eps(BFloat16)`
This is mainly to make code look nicer.
The function is as follows
`function eps(::Type{BFloat16})`
    `2^(-7)`
`end`
I'm not sure if this would be something worth adding to the file on GitHub especially since this is a pretty easy implementation. 
I also imported Base.eps at the top

If this is something I can do and is deemed beneficial, I can submit a pull request with these changes made.

**Comment by amontoison** [comment]
I already implemented the `eps` function inside #12 @jprhyne : 
```julia
eps(::Type{BFloat16}) = Base.bitcast(BFloat16, 0x3c00)
```
But no one seems available to review and merge pull requests.

**Comment by jprhyne** [comment]
Interesting. I can't see that on my end, nor in the master branch.

I'm relatively new to git (beyond just cloning repositories), so I assume there is an administrator for the repo that has to approve the requests?

**Comment by dpo** [comment]
Implemented in #12.
