### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by maleadt** [JuliaMath/BFloat16s.jl#31]
The changes from https://github.com/JuliaMath/BFloat16s.jl/commit/a32492ff13c66add607c20bc36b1db684a9de6e1 are required for BFloat16 comparisons (requiring a working `rtoldefault`).

**Comment by staticfloat** [comment]
Done in https://github.com/JuliaMath/BFloat16s.jl/commit/ef6051e4308ed0c02f10168b99d226237e0ae33c
