### ISSUE TITLE
Fix nonexistent overload of `Printf` functionality

### ISSUE THREAD

**Issue by Seelengrab** [JuliaMath/BFloat16s.jl#40]
https://github.com/JuliaMath/BFloat16s.jl/blob/ef6051e4308ed0c02f10168b99d226237e0ae33c/src/printf.jl#L10-L17

These lines should probably be replaced with functions from `Base.Ryu`. I think this has been broken since at least 1.6.

**Comment by JeffreySarnoff** [comment]
happy to do so -- no idea what to do though
